[package]
name = "torrentui"
version = "0.1.0"
authors = ["Sergei Shavlovskii <fucaluca@proton.me>"]
license = "MIT"
edition = "2024"
description = "A TUI client for torrents"

[dependencies]
arboard = { version = "3.6.1", features = [
  "wl-clipboard-rs",
  "wayland-data-control",
] }
async-trait = "0.1.89"
clap = { version = "4.5.60", features = ["env", "derive"] }
color-eyre = { version = "0.6.5" }
config = { version = "0.15.19", features = ["preserve_order"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
directories = "6.0.0"
fake = { version = "4.4.0", features = ["derive"] }
futures = "0.3.31"
indexmap = { version = "2.13.0", features = ["serde"] }
ratatui = "0.30.0"
# reqwest = { version = "0.13.2", features = ["json", "native-tls-vendored"] }
reqwest = { version = "0.13.1", default-features = false, features = [
  "rustls",
  "json",
] }
serde = { version = "1.0.228", features = ["derive"] }
snafu = "0.8.9"
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = "0.7.17"
tracing = "0.1.41"
tracing-error = "0.2.1"
tracing-journald = "0.3.2"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
url = "2.5.7"

[profile.dev]
debug = true
opt-level = 0

[dev-dependencies]
assert_matches = "1.5.0"
fake = { version = "4.4.0", features = ["derive"] }
hex = "0.4.3"
mockall = "0.14.0"
pretty_assertions = "1.4.1"
sha1 = "0.10.6"
tempdir = "0.3.7"
wiremock = "0.6.5"
