update_interval_secs = 1
notification_timeout_millis = 100
player_cmd = "setsid mpv"
show_help_auto = true
auto_insert_torrent = true

[keybindings.TorrentList]
"<k>" = "Up"
"<j>" = "Down"
"<up>" = "Up"
"<down>" = "Down"
"<g><g>" = "GotoTop"
"<g><e>" = "GotoBottom"
"<space><space>" = "PauseToggle"
"<space><o>" = "Play"
"<space><a>" = "AddTorrent"
"<ctrl-d>" = { description = "Delete torrent" }
"<ctrl-d><f>" = { action = "Forget", description = "Forget about the torrent, keep the files" }
"<ctrl-d><d>" = { action = "Delete", description = "Forget about the torrent, remove the files" }
"<esc>" = "Escape"
"<?>" = "Help"
"<q>" = "Quit"

[keybindings.AddTorrent.Input]
"<k>" = "Up"
"<j>" = "Down"
"<up>" = "Up"
"<down>" = "Down"
"<backspace>" = { action = "Backspace", description = "Clear" }
"<ctrl-v>" = "Paste"
"<enter>" = "Enter"
"<esc>" = "Escape"
"<?>" = "Help"

[keybindings.AddTorrent.Connectors]
"<k>" = "Up"
"<j>" = "Down"
"<up>" = "Up"
"<down>" = "Down"
"<space>" = { action = "Toggle", description = "Toggle selected" }
"<enter>" = "Send"
"<esc>" = "Escape"
"<tab>" = { action = "Switch", description = "Return to input magnet" }
"<?>" = "Help"

[connectors.localhost]
kind = "rqbit"
url = "http://localhost:3030"
api_version = "v8"
update_interval_secs = 1
selected_by_default = true

[styles.Active]
upload = "black on yellow"
download = "black on blue"

[styles.Paused]
default = "dark gray on rgb:0,0,0"

[styles.Notification]
info = "blue on rgb:0,0,0"
error = "red on rgb:0,0,0"

[styles.WhichKey]
key = "yellow on rgb:0,0,0"
description = "blue on rgb:0,0,0"
next = "magenta on rgb:0,0,0"
divider = "rgb:80,80,80 on rgb:0,0,0"
default = "blue on rgb:0,0,0"

[styles.Default]
default = "white on rgb:0,0,0"
highlight = "yellow on black"
dividers = "white on rgb:0,0,0"

[styles.AddTorrent.Input]
input_highlight = "black on white"
selected_connector = "gray on rgb:30,30,30"
insert_mode = "blue on rgb:30,30,30"
border = "blue on rgb:30,30,30"
default = "gray on rgb:30,30,30"

[styles.AddTorrent.Connectors]
input = "dark gray on rgb:30,30,30"
input_highlight = "dark gray on rgb:30,30,30"
selected_connector = "yellow on rgb:30,30,30"
connectors_highlight = "black on white"
border = "blue on rgb:30,30,30"
default = "blue on rgb:30,30,30"
